const data = {
    books:[
        {
            name:"All Quiet On the Western Front",
            slug:"all-quiet-on-the-western-front",
            genre:"war novel",
            image:"/images/img1.jpg",
            author:"Erich Maria Remarque",
            year:1928,
            price:250,
            stock:20,
            rating:9.2,
            review:24,
            desc:"A young German soldier of World War I tells of a generation of men who, even though they may have escaped shells, were destroyed by the war."
        },
        {
            name:"The Old Man and the Sea",
            author:"Ernest Hemingway",
            year:1952,
            genre:"novel",
            desc:"The Old Man and the Sea, short heroic novel by Ernest Hemingway, published in 1952 and awarded the 1953 Pulitzer Prize for fiction.",
            image:"/images/img2.jpg",
            slug:"the-old-man-and-the-sea",
            price:270,
            stock:27,
            rating:9.4,
            review:35,
            
        },
        {
            name:"Kafka on the Shore",
            slug:"kafka-on-the-shore",
            genre:"novel",
            image:"/images/img3.jpg",
            author:"Haruki Murakami",
            year:2002,
            price:200,
            stock:8,
            rating:8.8,
            review:45,
            desc:"KAFKA ON THE SHORE is a beautifully told story about needing to let go and step out of your own reality in order to find out that life is meant to be lived."
        },
        {
            name:"To Kill a Mockingbird",
            slug:"to-kill-a-mockingbird",
            genre:"novel",
            image:"/images/img4.jpg",
            author:"Harper Lee",
            year:1960,
            price:280,
            stock:15,
            rating:8.9,
            review:26,
            desc:"To Kill a Mockingbird is primarily a novel about growing up under extraordinary circumstances in the 1930s in the Southern United States."
        },
        {
            name:"All Quiet On the Western Front",
            slug:"all-quiet-on-the-western-front",
            genre:"war novel",
            image:"/images/img1.jpg",
            author:"Erich Maria Remarque",
            year:1928,
            price:250,
            stock:20,
            rating:9.2,
            review:24,
            desc:"A young German soldier of World War I tells of a generation of men who, even though they may have escaped shells, were destroyed by the war."
        },
        {
            name:"The Old Man and the Sea",
            author:"Ernest Hemingway",
            year:1952,
            genre:"novel",
            desc:"The Old Man and the Sea, short heroic novel by Ernest Hemingway, published in 1952 and awarded the 1953 Pulitzer Prize for fiction.",
            image:"/images/img2.jpg",
            slug:"the-old-man-and-the-sea",
            price:270,
            stock:27,
            rating:9.4,
            review:35,
            
        },
        {
            name:"Kafka on the Shore",
            slug:"kafka-on-the-shore",
            genre:"novel",
            image:"/images/img3.jpg",
            author:"Haruki Murakami",
            year:2002,
            price:200,
            stock:8,
            rating:8.8,
            review:45,
            desc:"KAFKA ON THE SHORE is a beautifully told story about needing to let go and step out of your own reality in order to find out that life is meant to be lived."
        },
        {
            name:"To Kill a Mockingbird",
            slug:"to-kill-a-mockingbird",
            genre:"novel",
            image:"/images/img4.jpg",
            author:"Harper Lee",
            year:1960,
            price:280,
            stock:15,
            rating:8.9,
            review:26,
            desc:"To Kill a Mockingbird is primarily a novel about growing up under extraordinary circumstances in the 1930s in the Southern United States."
        },
        {
            name:"All Quiet On the Western Front",
            slug:"all-quiet-on-the-western-front",
            genre:"war novel",
            image:"/images/img1.jpg",
            author:"Erich Maria Remarque",
            year:1928,
            price:250,
            stock:20,
            rating:9.2,
            review:24,
            desc:"A young German soldier of World War I tells of a generation of men who, even though they may have escaped shells, were destroyed by the war."
        },
        {
            name:"The Old Man and the Sea",
            author:"Ernest Hemingway",
            year:1952,
            genre:"novel",
            desc:"The Old Man and the Sea, short heroic novel by Ernest Hemingway, published in 1952 and awarded the 1953 Pulitzer Prize for fiction.",
            image:"/images/img2.jpg",
            slug:"the-old-man-and-the-sea",
            price:270,
            stock:27,
            rating:9.4,
            review:35,
            
        },
        {
            name:"Kafka on the Shore",
            slug:"kafka-on-the-shore",
            genre:"novel",
            image:"/images/img3.jpg",
            author:"Haruki Murakami",
            year:2002,
            price:200,
            stock:8,
            rating:8.8,
            review:45,
            desc:"KAFKA ON THE SHORE is a beautifully told story about needing to let go and step out of your own reality in order to find out that life is meant to be lived."
        },
        {
            name:"To Kill a Mockingbird",
            slug:"to-kill-a-mockingbird",
            genre:"novel",
            image:"/images/img4.jpg",
            author:"Harper Lee",
            year:1960,
            price:280,
            stock:15,
            rating:8.9,
            review:26,
            desc:"To Kill a Mockingbird is primarily a novel about growing up under extraordinary circumstances in the 1930s in the Southern United States."
        },
    ]
}

export default data